# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7356def7b17a744fb49172a9b43ac131789c9ef3122f4bf4f4994629e02a130f019be24617d1cfe30d195027c71fb0bd490b9adbf315f4894db460877b95ae9a

test:
  secret_key_base: 2034122050646ee488dc43262e6256894cfdfe90dddd3968d73d4da34078654172b79e70e1641cac6443808fa8ed5bf7d56c00d65e81422cf1f8451bc980ee73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
